build:
  image: framgia/ruby-workspace-ci
  commands:
    - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
    - bundle install --path=/drone/.bundle
    - framgia-ci run
cache:
  mount:
    - .git
    - /drone/.bundle
