user:
  name: 50
project:
  name: 100
time_sheet:
  employee_code: 7
  staff_name: 50
image_format_accept: "image/jpeg,image/gif,image/png"
image_width: 200
image_height: 200
per_page:
  admin:
    user: 10
min_password: 6
workspace:
  per_page: 3
