user:
  name: 50
project:
  name: 100
time_sheet:
  employee_code: 7
  staff_name: 50
image_format_accept: "image/jpeg,image/gif,image/png"
image_width: 200
image_height: 200
per_page:
  admin:
    user: 10
min_password: 6
workspace:
  per_page: 3
break_line: "<br>"
validation:
  workspace:
    name_max_len: 128
    des_max_len: 255
  section:
    name_max_len: 128
  position_type:
    name_max_len: 128
    color_max_len: 128
